### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ghost** [Fameless9/AllItems#2]
https://github.com/Fameless9/AllItems/blob/3470616eb58c284d4ac27f5f36ffd64f860e578b/src/main/java/net/fameless/allitems/command/StatsCommand.java#L132

Checking event.getView().getTitle() to see whether your custom inventory is being used is unsafe, as renaming a chest in an anvil allows users to set their own inventory titles. The correct way to check if your custom inventory is involved with an event is by using custom holders, see here: https://docs.papermc.io/paper/dev/custom-inventory-holder

**Comment by nicolaigrv** [comment]
Hi, thanks for reporting this. In this case it's not necessarily a security issue, as the plugin checks for sufficient permissions when a player clicks on an inventory that requires permission to open, but it may interfere with other plugins. This will be fixed as soon as possible.

**Comment by nicolaigrv** [comment]
Fixed in 1.0.4: https://github.com/Fameless9/AllItems/releases/tag/1.0.4
